I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 32, in script
    image megumin = Live2D("Live2D/megumin",loop=True)
  File "game/script.rpy", line 32, in <module>
    image megumin = Live2D("Live2D/megumin",loop=True)
Exception: Live2D model Live2D/megumin/megumin.model3.json does not exist.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 32, in script
    image megumin = Live2D("Live2D/megumin",loop=True)
  File "D:\ren\renpy-8.1.3-sdk\renpy\ast.py", line 1237, in execute
    img = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "D:\ren\renpy-8.1.3-sdk\renpy\python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 32, in <module>
    image megumin = Live2D("Live2D/megumin",loop=True)
  File "D:\ren\renpy-8.1.3-sdk\renpy\gl2\live2d.py", line 566, in __init__
    common = self.create_common(default_fade)
  File "D:\ren\renpy-8.1.3-sdk\renpy\gl2\live2d.py", line 510, in create_common
    rv = Live2DCommon(self.filename, default_fade)
  File "D:\ren\renpy-8.1.3-sdk\renpy\gl2\live2d.py", line 197, in __init__
    raise Exception("Live2D model {} does not exist.".format(filename))
Exception: Live2D model Live2D/megumin/megumin.model3.json does not exist.

Windows-10-10.0.19041 AMD64
Ren'Py 8.1.3.23091805
cyberWaifuClient 1.0
Thu Jan  4 18:36:15 2024
